version: '3.10'

services:
  web:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
